version: '3.7'

services:
  akhq:
    image: tchiotludo/akhq:latest
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka1:19092,kafka2:19093,kafka3:19094"
              schema-registry:
                url: "http://kafka-schema-registry:8081"
    ports:
      - "8089:8080"
    networks:
      - ${GLOBAL_NETWORK:-kafka}
